-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `mysql_ef`.`Posts` (
  `PostId` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` TEXT NULL DEFAULT NULL,
  `Content` TEXT NULL DEFAULT NULL,
  `BlogId` INT(11) NOT NULL,
  PRIMARY KEY (`PostId`),
  INDEX `IX_Posts_BlogId` (`BlogId` ASC),
  CONSTRAINT `FK_Posts_Blogs_BlogId`
    FOREIGN KEY (`BlogId`)
    REFERENCES `mysql_ef`.`Blogs` (`BlogId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

ALTER TABLE `mysql_ef`.`TestTable` 
ADD COLUMN `Url` VARCHAR(255) NULL DEFAULT NULL AFTER `Name`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
